<?php
$apiCalls = $debugWidget->getApiCalls();
?>
<div id='pdw-panel-api' class='pdw-panel api'>
    <div class='title'>
        <h2>API Info <a class='pdw-panel-close'>&times;</a></h2>
    </div>
    <div class='panel-content' style="overflow: auto;">
        <!--<h3 class='collapser'>--><?php //echo pathinfo($rendered['path'], PATHINFO_BASENAME); ?><!--</h3>-->
        <table class='pdw-data-table'>
            <thead>
            <tr>
                <th>Method</th>
                <th>URL</th>
                <th>Params</th>
                <th>Options</th>
                <th>Response</th>
                <th style="width: 100px">Time (s)</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($apiCalls as $apiCall): ?>
                <tr>
                    <td>
                        <?php echo strtoupper($apiCall['type']) ?>
                    </td>
                    <td>
                        <?php echo $apiCall['uri']->scheme . '://' . $apiCall['uri']->host . $apiCall['uri']->path ?>
                    </td>
                    <td>
                        <pre class="language-php"><code class="language-php"><?php print_r($apiCall['params']) ?></code></pre>
                    </td>
                    <td>
                        <?php foreach ($apiCall['options'] as $curlOpt => $curlVal) : ?>
                            <?php $apiCall['options'][$debugWidget->getCurlOption($curlOpt)] = $curlVal; ?>
                            <?php unset($apiCall['options'][$curlOpt]); ?>
                        <?php endforeach; ?>
                        <pre class="language-php"><code class="language-php"><?php print_r($apiCall['options']) ?></code></pre>
                    </td>
                    <td>
                        <pre style="overflow: auto; max-width: 500px; max-height: 180px;"><code class="language-php"><?php print_r($apiCall['response']) ?></code></pre>
                    </td>
                    <td>
                        <?php echo round($apiCall['time'], 6) ?>
                    </td>
                </tr>

                <?php //foreach ($apiCall as $k => $v) {
                //    $class = ($k == 'params') ? "language-php" : "";
                //    echo "<tr>";
                //    echo "<td style='width: 125px;'>{$k}</td>";
                //    echo "<td><pre><code class='{$class}'>";
                //    if ($k == 'curl_options') {
                //        foreach ($v as $curlOpt => $curlVal) {
                //            $v[$debugWidget->getCurlOption($curlOpt)] = $curlVal;
                //            unset($v[$curlOpt]);
                //        }
                //    }
                //
                //    print_r($v);
                //    echo "</code></pre></td>";
                //    echo "</tr>";
                //} ?>

            <?php endforeach; ?>
            <tr>
                <td><strong>Total:</strong></td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td><strong><?php echo round($debugWidget->getApiCallTime(), 6); ?></strong></td>
            </tr>
            </tbody>
        </table>
    </div>
</div>
